### ISSUE TITLE
Add propagate to nf-core/phageannotator to identify active prophage

### ISSUE THREAD

**Issue by CarsonJM** [nf-core/phageannotator#19]
Add propagate (https://github.com/AnantharamanLab/PropagAtE) module to workflow to predict integrated prophage activitiy

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/phageannotator/issues/57
- [ ] https://github.com/nf-core/phageannotator/issues/58
- [ ] https://github.com/nf-core/phageannotator/issues/59
```
