### ISSUE TITLE
Add nf-tests to nf-core/phageannotator's nf-core modules

### ISSUE THREAD

**Issue by CarsonJM** [nf-core/phageannotator#36]
The purpose of this enhancement is to ensure that all modules in phageannotator have nf-tests

```[tasklist]
### Tasks
- [x] https://github.com/nf-core/modules/issues/4620
- [x] Add nf-tests to nf-core/modules blast
- [x] Add nf-tests to nf-core/modules bowtie2
- [x] Add nf-tests to nf-core/modules cat/cat
- [ ] https://github.com/nf-core/modules/issues/4618
- [x] Add nf-tests to nf-core/modules fastqc
- [ ] https://github.com/nf-core/modules/issues/4673
- [x] Add nf-tests to nf-core/modules gunzip
- [ ] https://github.com/nf-core/modules/issues/4747
- [ ] https://github.com/nf-core/modules/issues/4930
- [ ] https://github.com/nf-core/modules/issues/4689
- [x] Add nf-tests to nf-core/modules multiqc
- [x] Add nf-tests to nf-core/modules samtools
- [x] Add nf-tests to nf-core/modules untar
```
