### ISSUE TITLE
Add UHGV classify to nf-core/phageannotator

### ISSUE THREAD

**Issue by CarsonJM** [nf-core/phageannotator#37]
UHGV classify (https://github.com/snayfach/UHGV) is a tool that can be used to compare _de novo_ phage sequences to a reference database. It finds the most similar UHGV sequences and annotates sequences based on reference properties. 

**Currently waiting for UHGV paper to be published**

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/phageannotator/issues/51
- [ ] https://github.com/nf-core/phageannotator/issues/52
- [ ] https://github.com/nf-core/phageannotator/issues/53
```
