### ISSUE TITLE
Add nf-core/phageannotator's local modules/subworkflows to nf-core

### ISSUE THREAD

**Issue by CarsonJM** [nf-core/phageannotator#39]
```[tasklist]
### Tasks
- [ ] Add coverm/contig to nf-core/modules
- [ ] Add coverm/genome to nf-core/modules
- [ ] Add mash/paste to nf-core/modules
- [ ] Add prodigal/prodigalgv to nf-core/modules
- [ ] Add seqkit/seq to nf-core/modules
- [ ] Add fasta_microdiversity_instrain to nf-core/modules
- [ ] Add fasta_virus_classification_genomad to nf-core/modules
- [ ] Add fasta_virus_quality_checkv to nf-core/modules
- [ ] Update mash/sketch in nf-core/modules
- [ ] Update mash/screen in nf-core/modules
```
