### ISSUE TITLE
Add mash reference database comparison to nf-core/phageannotator

### ISSUE THREAD

**Issue by CarsonJM** [nf-core/phageannotator#60]
The goal with this enhancement is to compare _de novo_ identified phage to a reference database to 1) find the closest reference counterpart 2) determine how novel a phage sequence is

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/phageannotator/issues/61
- [ ] https://github.com/nf-core/phageannotator/issues/62
- [ ] https://github.com/nf-core/phageannotator/issues/106
```
