### ISSUE TITLE
Add other phage identification options to nf-core/phageannotator

### ISSUE THREAD

**Issue by CarsonJM** [nf-core/phageannotator#67]
The purpose of this enhancement is to provide users with another popular tool for virus classification (https://github.com/jiarong/VirSorter2)

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/phageannotator/issues/68
- [ ] https://github.com/nf-core/phageannotator/issues/69
- [ ] Add PPR-Meta to nf-core/phageannotator
- [ ] Add viralverify to nf-core/phageannotator
- [ ] Add VIBRANT to nf-core/phageannotator
```
